### ISSUE TITLE
ModuleNotFoundError: No module named 'mautrix.client.api.types'

### ISSUE THREAD

**Issue by entropydo** [jeffcasavant/MaubotTrumpTweet#7]
Hello,

I tried installing your plugin into a fresh docker image from dock.mau.dev/maubot/maubot:latest. It runs perfectly and am able to load other plugins without difficulty.

I also made sure to install wkhtmltopdf on the docker image.

Thank you for your help!

```
ERRORloader.zipFailed to load casavant.jeff.trumptweet v1.0.4
15:20:56ERRORloader.zipTraceback (most recent call last):
  File "/opt/maubot/maubot/loader/zip.py", line 192, in _load
    importer.load_module(module)
  File "/opt/maubot/maubot/lib/zipimport.py", line 282, in load_module
    exec(code, mod.__dict__)
  File "/data/plugins/casavant.jeff.trumptweet-v1.0.4.mbp/plugin.py", line 14, in <module>
    from mautrix.client.api.types.event.message import MediaMessageEventContent
ModuleNotFoundError: No module named 'mautrix.client.api.types'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/maubot/maubot/loader/zip.py", line 177, in load
    return self._load(reset_cache)
  File "/opt/maubot/maubot/loader/zip.py", line 196, in _load
    raise MaubotZipLoadError(f"Failed to load module {module}")
maubot.loader.zip.MaubotZipLoadError: Failed to load module plugin
15:20:56ERROR@ : Failed to start
15:20:56ERROR@ : Traceback (most recent call last):
  File "/opt/maubot/maubot/loader/zip.py", line 192, in _load
    importer.load_module(module)
  File "/opt/maubot/maubot/lib/zipimport.py", line 282, in load_module
    exec(code, mod.__dict__)
  File "/data/plugins/casavant.jeff.trumptweet-v1.0.4.mbp/plugin.py", line 14, in <module>
    from mautrix.client.api.types.event.message import MediaMessageEventContent
ModuleNotFoundError: No module named 'mautrix.client.api.types'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/maubot/maubot/client.py", line 127, in start
    await self._start(try_n)
  File "/opt/maubot/maubot/client.py", line 190, in _start
    await self.start_plugins()
  File "/opt/maubot/maubot/client.py", line 193, in start_plugins
    await asyncio.gather(*[plugin.start() for plugin in self.references])
  File "/opt/maubot/maubot/instance.py", line 162, in start
    cls = await self.loader.load()
  File "/opt/maubot/maubot/loader/zip.py", line 177, in load
    return self._load(reset_cache)
  File "/opt/maubot/maubot/loader/zip.py", line 196, in _load
    raise MaubotZipLoadError(f"Failed to load module {module}")
maubot.loader.zip.MaubotZipLoadError: Failed to load module plugin
```

**Comment by jeffcasavant** [comment]
This is related to some breaking changes in the mautrix library which I haven't yet updated for.

**Comment by entropydo** [comment]
> 
> 
> This is related to some breaking changes in the mautrix library which I haven't yet updated for.

Anything I can help out with? Thanks for the super quick response!

**Comment by jeffcasavant** [comment]
If you're up for some development, by all means!  I expect most of the imports from the Mautrix library will have to change, but that's about it.

**Comment by Takalele** [comment]
Hi,

you just need to edit two files:
plugin.py
line 14 from:
`from mautrix.client.api.types import MediaMessageEventContent, ImageInfo`
to:
`from mautrix.types.event.message import MediaMessageEventContent, ImageInfo`

and 
maubot.yaml
line 3 from:
`version: 1.0.4`
to:
`version: 1.0.5`

then rebuild it and install it.
mbc build MaubotTrumpTweet-master

BR
Takalele
[casavant.jeff.trumptweet-v1.0.5.mbp.zip](https://github.com/jeffcasavant/MaubotTrumpTweet/files/5719892/casavant.jeff.trumptweet-v1.0.5.mbp.zip)

**Comment by jeffcasavant** [comment]
@Takalele You've basically submitted a PR here - I can handle that if you don't want to actually do it, but you're pretty much already there.

I'll try and knock it out by EOD today, so jump on it if you want the PR.
